name: "Build & Test"
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Verify Formatting
      shell: bash
      run: deno fmt --check --ignore="external-libraries.plug.js,test-space/"

    - name: Run Tests
      shell: bash
      run: deno test --coverage=cov_profile

    - name: Coverage
      shell: bash
      run: deno coverage --html cov_profile/

    - name: Convert HTML to Markdown
      id: html2markdown
      uses: rknj/html2markdown@v0.1.0
      with:
        html-file: "./cov_profile/html/index.html"

    - name: Write to Job Summary
      shell: bash
      run: echo "${{ steps.html2markdown.outputs.markdown-content }}" >> $GITHUB_STEP_SUMMARY

    - name: Setup SilverBullet
      shell: bash
      run: deno install -f --global --name silverbullet  --unstable-kv --unstable-worker-options -A https://get.silverbullet.md

    - name: Add Deno to PATH
      shell: bash
      run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

    - name: Show Silverbullet Version
      shell: bash
      run: silverbullet --version

    - name: Build Plug
      shell: bash
      run: deno task build:release
