name: "Build & Test"
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Verify Formatting
      shell: bash
      run: deno fmt --check --ignore="external-libraries.plug.js,test-space/"

    - name: Run Tests
      shell: bash
      run: deno test --coverage=cov_profile

    - name: Coverage
      shell: bash
      run: deno coverage --lcov cov_profile/ > cov.lcov

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: cov.lcov
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: false
        output: file

    - name: Write to Job Summary
      shell: bash
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Setup SilverBullet
      shell: bash
      run: deno install -f --global --name silverbullet  --unstable-kv --unstable-worker-options -A https://get.silverbullet.md

    - name: Add Deno to PATH
      shell: bash
      run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

    - name: Show Silverbullet Version
      shell: bash
      run: silverbullet --version

    - name: Build Plug
      shell: bash
      run: deno task build:release
