name: Update Plug

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: "Build & Test"
        uses: "./.github/actions/build-test"

      - name: "Check if plug has changed"
        shell: pwsh
        id: check_plug
        run: |
          $diff = git diff --name-only
          $SourceDiff = $diff | Where-Object { $_ -eq "external-libraries.plug.js" }
          $HasDiff = $SourceDiff.Length -gt 0
          Add-Content -Path $env:GITHUB_OUTPUT -Value "has_changed=$HasDiff"
          Write-Host "Plug has changed? $HasDiff"

      - name: Commit and push if on main
        if: steps.check_plug.outputs.has_changed == 'True'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add external-libraries.plug.js || true
          git commit -m "Auto update plug.js [skip ci]" || true

      - name: Push changes with Git CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
